// <auto-generated />
using System;
using Cbo.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cbo.API.Migrations
{
    [DbContext(typeof(CboDbContext))]
    [Migration("20260820143411_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cbo.API.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedOnStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_on_stage");

                    b.Property<int>("NumberInStage")
                        .HasColumnType("integer")
                        .HasColumnName("number_in_stage");

                    b.Property<int>("NumberInTournament")
                        .HasColumnType("integer")
                        .HasColumnName("number_in_tournament");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_matches_tournament_id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<decimal?>("PointsSum")
                        .HasColumnType("numeric")
                        .HasColumnName("points_sum");

                    b.Property<Guid?>("PromotedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("promoted_from_id");

                    b.Property<int?>("ScoreSum")
                        .HasColumnType("integer")
                        .HasColumnName("score_sum");

                    b.Property<Guid>("TournamentParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_participant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_match_participants");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_participants_match_id");

                    b.HasIndex("PromotedFromId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_participants_promoted_from_id");

                    b.HasIndex("TournamentParticipantId")
                        .HasDatabaseName("ix_match_participants_tournament_participant_id");

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("CostNegative")
                        .HasColumnType("integer")
                        .HasColumnName("cost_negative");

                    b.Property<int>("CostPositive")
                        .HasColumnType("integer")
                        .HasColumnName("cost_positive");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("question_number");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_questions_topic_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOverrideMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_override_mode");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("NumberInMatch")
                        .HasColumnType("integer")
                        .HasColumnName("number_in_match");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_rounds_match_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_rounds_topic_id");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.RoundAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsAnswerAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_answer_accepted");

                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_participant_id");

                    b.Property<int?>("OverrideCost")
                        .HasColumnType("integer")
                        .HasColumnName("override_cost");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_round_answers");

                    b.HasIndex("MatchParticipantId")
                        .HasDatabaseName("ix_round_answers_match_participant_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_round_answers_question_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_round_answers_round_id");

                    b.ToTable("round_answers", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TopicAuthor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_author");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topic_authors");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_topic_authors_application_user_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_topic_authors_topic_id");

                    b.ToTable("topic_authors", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Preparations")
                        .HasColumnName("current_stage");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("PlayersPerTournament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("players_per_tournament");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TopicsPerParticipantMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("topics_per_participant_max");

                    b.Property<int>("TopicsPerParticipantMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("topics_per_participant_min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tournaments");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TournamentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("PointsSum")
                        .HasColumnType("numeric")
                        .HasColumnName("points_sum");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Player")
                        .HasColumnName("role");

                    b.Property<int?>("ScoreSum")
                        .HasColumnType("integer")
                        .HasColumnName("score_sum");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tournament_participants");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_tournament_participants_application_user_id");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_tournament_participants_tournament_id");

                    b.ToTable("tournament_participants", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TournamentTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<int>("PriorityIndex")
                        .HasColumnType("integer")
                        .HasColumnName("priority_index");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<Guid>("TournamentParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_participant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tournament_topics");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_tournament_topics_topic_id");

                    b.HasIndex("TournamentParticipantId")
                        .HasDatabaseName("ix_tournament_topics_tournament_participant_id");

                    b.HasIndex("TournamentId", "TopicId", "TournamentParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_topics_tournament_id_topic_id_tournament_partici");

                    b.ToTable("tournament_topics", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Match", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_tournaments_tournament_id");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.MatchParticipant", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.Match", "Match")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_matches_match_id");

                    b.HasOne("Cbo.API.Models.Domain.MatchParticipant", "PromotedFrom")
                        .WithOne("PromotedTo")
                        .HasForeignKey("Cbo.API.Models.Domain.MatchParticipant", "PromotedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_participants_match_participants_promoted_from_id");

                    b.HasOne("Cbo.API.Models.Domain.TournamentParticipant", "TournamentParticipant")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("TournamentParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_tournament_participants_tournament_parti");

                    b.Navigation("Match");

                    b.Navigation("PromotedFrom");

                    b.Navigation("TournamentParticipant");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Question", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_topics_topic_id");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Round", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.Match", "Match")
                        .WithMany("Rounds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_matches_match_id");

                    b.HasOne("Cbo.API.Models.Domain.Topic", "Topic")
                        .WithMany("Rounds")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_topics_topic_id");

                    b.Navigation("Match");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.RoundAnswer", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.MatchParticipant", "MatchParticipant")
                        .WithMany("RoundAnswers")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_answers_match_participants_match_participant_id");

                    b.HasOne("Cbo.API.Models.Domain.Question", "Question")
                        .WithMany("RoundAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_answers_questions_question_id");

                    b.HasOne("Cbo.API.Models.Domain.Round", "Round")
                        .WithMany("RoundAnswers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_answers_rounds_round_id");

                    b.Navigation("MatchParticipant");

                    b.Navigation("Question");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TopicAuthor", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", "ApplicationUser")
                        .WithMany("TopicAuthors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_authors_application_user_application_user_id");

                    b.HasOne("Cbo.API.Models.Domain.Topic", "Topic")
                        .WithMany("TopicAuthors")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_authors_topics_topic_id");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TournamentParticipant", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", "ApplicationUser")
                        .WithMany("TournamentParticipants")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_participants_application_user_application_user_id");

                    b.HasOne("Cbo.API.Models.Domain.Tournament", "Tournament")
                        .WithMany("TournamentParticipants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_participants_tournaments_tournament_id");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TournamentTopic", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.Topic", "Topic")
                        .WithMany("TournamentTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_topics_topics_topic_id");

                    b.HasOne("Cbo.API.Models.Domain.Tournament", "Tournament")
                        .WithMany("TournamentTopics")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_topics_tournaments_tournament_id");

                    b.HasOne("Cbo.API.Models.Domain.TournamentParticipant", "TournamentParticipant")
                        .WithMany("TournamentTopics")
                        .HasForeignKey("TournamentParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_topics_tournament_participants_tournament_partic");

                    b.Navigation("Topic");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentParticipant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Cbo.API.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.ApplicationUser", b =>
                {
                    b.Navigation("TopicAuthors");

                    b.Navigation("TournamentParticipants");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Match", b =>
                {
                    b.Navigation("MatchParticipants");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.MatchParticipant", b =>
                {
                    b.Navigation("PromotedTo");

                    b.Navigation("RoundAnswers");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Question", b =>
                {
                    b.Navigation("RoundAnswers");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Round", b =>
                {
                    b.Navigation("RoundAnswers");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Topic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Rounds");

                    b.Navigation("TopicAuthors");

                    b.Navigation("TournamentTopics");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentParticipants");

                    b.Navigation("TournamentTopics");
                });

            modelBuilder.Entity("Cbo.API.Models.Domain.TournamentParticipant", b =>
                {
                    b.Navigation("MatchParticipants");

                    b.Navigation("TournamentTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
